name: Build in x86

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --prefix=$PWD/bin
    - name: make
      run: make
    - name: make distcheck
      run: make distcheck
    - name: make install
      run: make install
    - name: Archive binaries
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: ./bin

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download can utils artifact
      uses: actions/download-artifact@v3
      with:
        name: binaries
    - name: test vcan
      run: |
        ls -l bin
        chmod a+x bin/*
        sudo apt-get install -y linux-modules-extra-$(uname -r)
        sudo modprobe vcan
        lsmod | grep vcan
        sudo ip link add dev vcan0 type vcan
        sudo ip link set vcan0 mtu 16
        sudo ip link set up vcan0
        ifconfig vcan0
        ./bin/candump vcan0 &
        ./bin/cansend vcan0 5A2#11.2233.445D556677.66
