name: Build in x86

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make distcheck
      run: make distcheck
    - uses: actions/cache@v3
      id: restore-build
      with:
        path: ./can-utils-trunk.tar.gz
        key: restore-build

  testsetup:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - if: ${{ steps.restore-build.outputs.cache-hit != 'true' }}
      run: |
        tar -xf can-utils-trunk.tar.gz
    - name: test
      run: |
        sudo apt-get install -y linux-modules-extra-$(uname -r)
        sudo modprobe vcan
        lsmod | grep vcan
        sudo ip link add dev vcan0 type vcan
        sudo ip link set vcan0 mtu 16
        sudo ip link set up vcan0
        ifconfig vcan0
        ./candump vcan0 &
        ./cansend vcan0 5A2#11.2233.445D556677.66
        
